version: "3.7"
services:
    blog-mysql: 
        image: "mysql:latest"
        ports:
            - "3306:3306"
        command: "--default-authentication-plugin=mysql_native_password --init-file /DB/BlogDB.sql"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "blog_service"
            MYSQL_PASSWORD: "root"
        volumes:
            - "./BlogDB.sql:/DB/BlogDB.sql"
    blog-service:
        build: .
        command: sh -c "./wait-for.sh blog-mysql:3306 -- ./Ri-Blog"
        depends_on:
            - blog-mysql
        ports:
            - "8000:8000"
